#!/usr/bin/env python3
"""Scaffold an output project for converted Figma screens.

    python3 new_project.py --name acme-checkout --dir rtl --figma-url "https://figma.com/design/..."

Creates (under ~/Design/figma-html by default):

    <name>/
      project.json     what this project is, and where it came from
      tokens.css       the design system, filled from Figma Variables
      base.css         the shared reset — deliberately small
      screens/         one HTML file per screen
      assets/          images and icons
      .fidelity/       reference renders, diffs, per-screen reports
      README-dev.md    what the developer receives

Refuses to touch an existing project unless --force is passed.
"""

import argparse
import datetime
import json
import os
import re
import sys

BASE_CSS = """/* base.css — shared reset.
   Kept deliberately small: every rule here is one more thing that can make the
   render disagree with Figma. Add nothing that is not needed by every screen. */

*, *::before, *::after { box-sizing: border-box; }
html, body, h1, h2, h3, h4, h5, h6, p, figure, blockquote, dl, dd { margin: 0; }
ul[role="list"], ol[role="list"] { list-style: none; padding: 0; }

body {
  min-height: 100%;
  /* Figma antialiases text the way macOS does with -webkit-font-smoothing:
     antialiased. Without this line, text renders ~1 subpixel heavier in Chrome
     and every text block shows up in the pixel diff. */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  background: var(--surface-page, #fff);
}

img, picture, svg, video, canvas { display: block; max-width: 100%; }
input, button, textarea, select { font: inherit; color: inherit; }
button { background: none; border: 0; padding: 0; cursor: pointer; }
a { color: inherit; }

/* Visible focus, always. A converted screen that cannot be tabbed through is
   not a handoff-ready screen. */
:focus-visible { outline: 2px solid var(--focus-ring, #0d99ff); outline-offset: 2px; }
"""

TOKENS_CSS = """/* tokens.css — the design system, read from this Figma file's Variables.
   Generated by the figma-b-html skill. Every value a screen uses should come
   from here as var(--token); a raw hex in a screen file is a bug.

   Source: {source}
   Written: {when}

   Sections are filled in during the token pass. An empty section means the
   Figma file exposed no Variables of that kind — say so, do not invent them. */

:root {{
  color-scheme: light;

  /* --- colour --- */

  /* --- typography --- */

  /* --- spacing --- */

  /* --- radius --- */

  /* --- elevation --- */
}}
"""

README = """# {title}

Converted from Figma to HTML. **Static screens — no framework, no build step.**
Open any file in `screens/` directly in a browser, or open `index.html` for the
gallery of all of them.

- **Source:** {source}
- **Direction:** `{direction}`
- **Converted:** {when}

## What is here

| | |
|---|---|
| `index.html` | gallery — every screen, with its fidelity score |
| `tokens.css` | the design system as CSS custom properties, read from Figma Variables |
| `base.css` | shared reset, intentionally minimal |
| `screens/*.html` | one file per screen |
| `assets/` | images and icons used by the screens |
| `.fidelity/` | the proof: Figma reference, HTML render, pixel diff, per-screen report |

## For the developer

Every screen links `tokens.css` then `base.css` then its own inline `<style>`.
Values come through `var(--token)` — the token names are Figma's own, so they
map to whatever the design system is called in your codebase.

**Read `.fidelity/<screen>/report.json` before assuming a screen is exact.** Each
one records the measured pixel difference against the Figma render and lists
anything that could not be reproduced in a browser. Known deviations are stated,
never hidden.
"""

PROJECT_JSON_HINT = "written by figma-b-html; safe to edit by hand"


def slugify(value):
    value = re.sub(r"[^\w\s-]", "", value, flags=re.UNICODE).strip().lower()
    value = re.sub(r"[\s_]+", "-", value)
    return re.sub(r"-{2,}", "-", value) or "project"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True, help="project name (becomes the folder name)")
    ap.add_argument("--root", default=os.path.expanduser("~/Design/figma-html"))
    ap.add_argument("--dir", dest="direction", choices=["rtl", "ltr"], default="ltr")
    ap.add_argument("--title", default=None, help="human title for the gallery")
    ap.add_argument("--figma-url", default="", help="the file or page URL this came from")
    ap.add_argument("--force", action="store_true", help="allow writing into an existing folder")
    args = ap.parse_args()

    slug = slugify(args.name)
    root = os.path.abspath(os.path.expanduser(args.root))
    path = os.path.join(root, slug)
    title = args.title or args.name
    when = datetime.date.today().isoformat()
    source = args.figma_url or "(not recorded)"

    if os.path.exists(path) and not args.force:
        sys.stderr.write(
            "project already exists: %s\n"
            "Pass --force only after checking with the user — this folder holds their work.\n"
            % path
        )
        sys.exit(1)

    for sub in ("", "screens", "assets", ".fidelity"):
        os.makedirs(os.path.join(path, sub), exist_ok=True)

    def write(rel, content):
        full = os.path.join(path, rel)
        if os.path.exists(full) and not args.force:
            print("kept existing %s" % rel)
            return
        with open(full, "w") as fh:
            fh.write(content)

    write("base.css", BASE_CSS)
    write("tokens.css", TOKENS_CSS.format(source=source, when=when))
    write("README-dev.md", README.format(
        title=title, source=source, direction=args.direction, when=when))
    write("project.json", json.dumps({
        "_": PROJECT_JSON_HINT,
        "name": slug,
        "title": title,
        "direction": args.direction,
        "figma_url": args.figma_url,
        "created": when,
        # What he asked for, settled once per file by the intent gate and
        # inherited by every screen in the batch. mode: as-is | responsive |
        # states | full. An empty breakpoints list means he was asked and had
        # no frames — never that the question was skipped.
        "intent": {"mode": "as-is", "breakpoints": [], "states": False, "asked": None},
        "screens": [],
    }, indent=2, ensure_ascii=False) + "\n")

    print(path)


if __name__ == "__main__":
    main()
